// Old school actions
_source addAction ["---- Change de rôle mk1------", ""];
_source addAction ["- Rifleman - Carbine", "\CGQC_2022\loadouts\mk1_rifleman_carbine.sqf"];
_source addAction ["- Rifleman - CQB", "\CGQC_2022\loadouts\mk1_rifleman_cqb.sqf"];
_source addAction ["- Medic", "\CGQC_2022\loadouts\mk1_medic.sqf"];
_source addAction ["- Engineer", "\CGQC_2022\loadouts\mk1_engineer.sqf"];
_source addAction ["- HQ/MobileSat", "\CGQC_2022\loadouts\mk1_hq.sqf"];
_source addAction ["- Squad Leader", "\CGQC_2022\loadouts\mk1_squad_leader.sqf"];
_source addAction ["- Drone Operator", "\CGQC_2022\loadouts\mk1_drone_operator.sqf"];
_source addAction ["- Team/Squad Leader", "\CGQC_2022\loadouts\mk1_tl.sqf"];
_source addAction ["- Team/Squad Leader CQB", "\CGQC_2022\loadouts\mk1_tl_cqb.sqf"];
_source addAction ["- MG (Light)", "\CGQC_2022\loadouts\mk1_lmg.sqf"];
_source addAction ["- MG (Heavy)", "\CGQC_2022\loadouts\mk1_hmg.sqf"];
_source addAction ["- Marksman", "\CGQC_2022\loadouts\mk1_marksman.sqf"];
_source addAction ["- Sniper", "\CGQC_2022\loadouts\mk1_sniper.sqf"];
_source addAction ["- Anti-Tank (MAAWS)", "\CGQC_2022\loadouts\mk1_at_maaws.sqf"];
_source addAction ["- Anti-Tank (Javelin)", "\CGQC_2022\loadouts\mk1_at_javelin.sqf"];
_source addAction ["- Helicopter Pilot", "\CGQC_2022\loadouts\mk1_heli_pilot.sqf"];
_source addAction ["- Helicopter Crew", "\CGQC_2022\loadouts\mk1_heli_crew.sqf"];
_source addAction ["- Jet Pilot", "\CGQC_2022\loadouts\mk1_jet_pilot.sqf"];
_source addAction ["- Tank Driver/Crew", "\CGQC_2022\loadouts\mk1_driver_tank.sqf"];