cgqc_mk2_arsenal_1_items = [
    // Radios -----------------------------------
    "ACRE_PRC343", 
    "ACRE_PRC152",
    "ACRE_PRC117F",
    // Meds -----------------------------------
    "ACE_fieldDressing", 
    "ACE_epinephrine", 
    "ACE_morphine", 
    "ACE_splint", 
    "ACE_tourniquet",
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
    "FF_Painkiller",
    "ACE_personalAidKit",
    // Items -----------------------------------
    "ACE_EarPlugs",
    "ACE_CableTie",
    "ACE_MapTools",
    "ACE_EntrenchingTool",
    "grad_paceCountBeads_functions_paceCountBeads",
    "ToolKit", 
    "ACE_DefusalKit", 
    "ACE_RangeCard", 
    "ACE_RangeTable_82mm",  
    "ACE_artilleryTable",
    "ACE_Canteen",    
    "ACE_SpottingScope", 
    "ACE_SpraypaintBlack", 
    "ACE_SpraypaintBlue", 
    "ACE_SpraypaintGreen",
    "ACE_SpraypaintRed",
    "ACE_Tripod", 
    "ACE_UAVBattery", 
    "ACE_wirecutter", 
    "murshun_cigs_cigpack",
    "murshun_cigs_lighter",
    "acex_intelitems_notepad",
    // Electronics ------------------------------
    "ItemAndroid", 
    "ACE_microDAGR",
    "ItemcTab",
    "WBK_HeadLampItem",
    "ACE_ATragMX", 
    "ACE_Kestrel4500",
    "ACE_Flashlight_MX991", 
    "ACE_Flashlight_XL50",
    "ACE_M26_Clacker",
    // Drones ------------------------------
    "sps_black_hornet_01_Static_F",
    "Rev_darter_item",
    "Rev_pelican_item",
    // Binoculars ------------------------------
    "Binocular",
    "cgqc_item_rangefinder",
    "Laserdesignator_01_khk_F",
    "Laserdesignator_01_khk_F", 
    "Laserdesignator_03", 
    "Laserdesignator" ,
    "ACE_Vector",
    "ACE_VectorDay",
    // NVG ------------------------------
    "NVGoggles_mas_can_hv", 
    "JAS_GPNVG18_blk",
    "JAS_GPNVG18_tan",
    "JAS_GPNVG18_Full_blk_TI",
    "JAS_GPNVG18_Full_tan_TI",
    // Linked items ------------------------------------
    "ItemMap", 
    "ItemGPS", 
    "ItemCompass", 
    "ItemWatch", 
    "ACE_Altimeter",
    "ChemicalDetector_01_watch_F",
    "B_UavTerminal"
];