// - Uniformes/Vestes/Backpacks de base
cgqc_mk2_arsenal_1_uniforms = [ 
    // Uniforms -----------------------------------
    "cgqc_uniform_mk1",
    "cgqc_uniform_mk1_desert", 
    "cgqc_uniform_mk1_mcam", 
    "cgqc_uniform_mk1_cadpat", 
    "cgqc_uniform_mk1_black", 
    "cgqc_uniform_mk1_white",
    "U_C_CBRN_Suit_01_Blue_F", 
    "U_B_CBRN_Suit_01_Wdl_F", 
    "U_B_CBRN_Suit_01_Tropic_F", 
    "U_B_CBRN_Suit_01_MTP_F",
    // Vests -----------------------------------
    "cgqc_vest_mk1_belt", 
    "cgqc_vest_mk1_tan",
    "cgqc_vest_mk1_tan_lr",
    "cgqc_vest_mk1_tan_rf",
    "cgqc_vest_mk1_tan_ar",
    "cgqc_vest_mk1_mcam", 
    "cgqc_vest_mk1_mcam_lr", 
    "cgqc_vest_mk1_mcam_rf", 
    "cgqc_vest_mk1_mcam_ar", 
    "cgqc_vest_mk1_cadpat", 
    "cgqc_vest_mk1_cadpat_lr", 
    "cgqc_vest_mk1_cadpat_rf", 
    "cgqc_vest_mk1_cadpat_ar", 
    "cgqc_vest_mk1_black", 
    "cgqc_vest_mk1_black_lr", 
    "cgqc_vest_mk1_black_rf", 
    "cgqc_vest_mk1_black_ar", 
    "cgqc_vest_mk1_white", 
    "cgqc_vest_mk1_white_lr", 
    "cgqc_vest_mk1_white_rf", 
    "cgqc_vest_mk1_white_ar",
    // Backpacks -----------------------------------
    "cgqc_pack_mk1_magic",
    "cgqc_pack_mk1_kitbag",
    "CGQC_units_mk1_4_Pilot_heli_pack", 
    "cgqc_pack_mk1_kitbag_desert", 
    "cgqc_pack_mk1_kitbag_mcam", 
    "cgqc_pack_mk1_kitbag_mcam", 
    "cgqc_pack_mk1_kitbag_cadpat", 
    "cgqc_pack_mk1_kitbag_black", 
    "cgqc_pack_mk1_kitbag_white", 
    "cgqc_pack_mk1_assault",
    "cgqc_pack_mk1_assault_desert",	
    "cgqc_pack_mk1_assault_mcam", 
    "cgqc_pack_mk1_assault_cadpat",
    "cgqc_pack_mk1_assault_black", 
    "cgqc_pack_mk1_assault_white"
];