cgqc_mk2_arsenal_1_guns = [
    // Pistols ---------------------------------------------------------------------
    "cgqc_gun_glock19_wood",
    "cgqc_gun_p99_wood",
    "hgun_mas_can_p226_F",
    // --- Ammo 
    "Tier1_15Rnd_9x19_JHP", 
    "Tier1_20Rnd_9x19_JHP", 
    "16Rnd_9x21_Mag", 
    "16Rnd_9x21_red_Mag",
    "16Rnd_9x21_green_Mag",
    // 5.56 ---------------------------------------------------------------------
    "cgqc_gun_mk1_m4a1blkII",  
    "cgqc_gun_mk1_mk18",  
    "cgqc_gun_mk1_mk18_fortin",
    "cgqc_gun_mk1_mk12", 
    "cgqc_gun_mk1_m16a4",
    "rhs_weap_m4a1_blockII",
    "rhs_weap_m4a1_blockII_d", 
    "rhs_weap_m4a1_blockII_wd", 
    "rhs_weap_m4a1_blockII_KAC_d", 
    "rhs_weap_m4a1_blockII_KAC_wd",
    "rhs_weap_m4", 
    "rhs_weap_m4a1_carryhandle", 
    "rhs_weap_mk18",
    "rhs_weap_mk18_d", 
    "rhs_weap_mk18_KAC_d", 
    "rhs_weap_mk18_wd", 
    "rhs_weap_mk18_KAC_wd",
    "Tier1_SR16_Carbine_Mod2_MFT_Black", 
    "Tier1_SR16_CQB_Mod2_MFT_Black",
    "Tier1_SR16_Carbine_Mod2_LMT_FDE", 
    "Tier1_SR16_Carbine_Mod2_LMT_Black", 
    "Tier1_SR16_Carbine_Mod2_IMOD_FDE", 
    "Tier1_SR16_Carbine_Mod2_IMOD_Black", 
    "Tier1_SR16_Carbine_Mod2_CTR_FDE", 
    "Tier1_SR16_Carbine_Mod2_CTR_Black", 
    "Tier1_SR16_Carbine_Mod2_MFT_FDE", 
    "Tier1_SR16_CQB_Mod2_CTR_Black", 
    "Tier1_SR16_CQB_Mod2_CTR_FDE", 
    "Tier1_SR16_CQB_Mod2_IMOD_Black", 
    "Tier1_SR16_CQB_Mod2_IMOD_FDE", 
    "Tier1_SR16_CQB_Mod2_LMT_Black", 
    "Tier1_SR16_CQB_Mod2_LMT_FDE", 
    "Tier1_SR16_CQB_Mod2_MFT_FDE",
    "Tier1_HK416D10_SMR_MFT", 
    "Tier1_HK416D145_SMR_MFT",
    // 5.56 Grenade-Launcher ----------------------------------------------------
    "UK3CB_ACR_Carbine_UGL",
    "cgqc_gun_mk1_mk18_gl",
    "cgqc_gun_mk1_m4a1blkII_gl",
    "rhs_weap_m4a1_blockII_M203", 
    "rhs_weap_m4a1_blockII_M203_wd", 
    "rhs_weap_m4a1_blockII_M203_d",
    "rhs_weap_m4_m203", 
    "rhs_weap_m4_m203S", 
    "rhs_weap_m4_m320", 
    "rhs_weap_m4a1_carryhandle_m203", 
    "rhs_weap_m4a1_carryhandle_m203S",
    // --- Ammo 
    "rhs_mag_30Rnd_556x45_Mk262_PMAG",
    "rhs_mag_30Rnd_556x45_Mk318_PMAG",
    // Grenades for launcher ---------
    "1Rnd_HE_Grenade_shell",
    "UGL_FlareRed_F", 
    "1Rnd_Smoke_Grenade_shell",  
    "1Rnd_SmokeBlue_Grenade_shell",
    "1Rnd_SmokeRed_Grenade_shell",  
    "1Rnd_SmokeGreen_Grenade_shell", 
    "1Rnd_SmokeYellow_Grenade_shell", 
    "1Rnd_SmokePurple_Grenade_shell", 
    "1Rnd_SmokeOrange_Grenade_shell",
    "3Rnd_SmokeBlue_Grenade_shell",
    "3Rnd_SmokeRed_Grenade_shell",
    "3Rnd_SmokePurple_Grenade_shell",
    // Launchers --------------------------------------------------------------------------
    "rhs_weap_m72a7",
    "rhs_weap_M136",
    // --- Launcher Ammo --------------------------------------------------------------------
    "MRAWS_HEAT_F",
    "MRAWS_HE_F",
    "MRAWS_HEAT55_F",
    "jav_AT_mas_can",
    "Titan_AA",
    // --- MG Ammo  --------------------------------------------------------------------
    "rhsusf_100Rnd_556x45_mixed_soft_pouch",
    "rhsusf_200Rnd_556x45_mixed_soft_pouch",
    "rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",
    "rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",
    "rhsusf_100Rnd_556x45_mixed_soft_pouch_ucp",
    "rhsusf_200Rnd_556x45_mixed_soft_pouch_ucp",
    "rhsusf_100Rnd_762x51", 
    "rhsusf_100Rnd_762x51_m61_ap", 
    "rhsusf_100Rnd_762x51_m62_tracer", 
    "rhsusf_100Rnd_762x51_m80a1epr", 
    "200Rnd_65x39_cased_Box", 
    "200Rnd_65x39_cased_Box_Tracer", 
    "200Rnd_65x39_cased_Box_Red", 
    "200Rnd_65x39_cased_Box_Tracer_Red", 
    "ACE_200Rnd_65x39_cased_Box_Tracer_Dim"
]; 