cgqc_mk2_arsenal_1_explosives = [
    // Throwables -----------------------------------
    "ACE_M84",
    "ACE_CTS9", 
    "MiniGrenade",
    "rhs_mag_m67",
    "B_IR_Grenade",
    "ACE_IR_Strobe_Item",
    "SmokeShell", 
    "SmokeShellBlue", 
    "SmokeShellRed", 
    "SmokeShellGreen", 
    "SmokeShellOrange", 
    "SmokeShellPurple", 
    "SmokeShellYellow",
    "Chemlight_blue", 
    "Chemlight_green", 
    "ACE_Chemlight_HiRed", 
    "ACE_Chemlight_IR", 
    "ACE_Chemlight_HiBlue", 
    "ACE_Chemlight_HiGreen", 
    "ACE_Chemlight_HiWhite", 
    "ACE_Chemlight_HiYellow", 
    "ACE_Chemlight_UltraHiOrange", 
    "ACE_HandFlare_Green", 
    "ACE_HandFlare_Red", 
    "ACE_HandFlare_White", 
]; 