// Rang 3 - CplC - Marksman/Engineer/Medic/Crew
cgqc_mk2_arsenal_rank3 = [
    // Radios -----------------------------------
    "ACRE_PRC152",
    // Engineer items ---------------------------
    "ToolKit", 
    "ACE_DefusalKit",
    "ACE_M26_Clacker",
    // Meds -----------------------------------
    "ACE_epinephrine", 
    "ACE_morphine", 
    "ACE_salineIV",
    "ACE_salineIV_250",
    "ACE_salineIV_500",
     "ACE_personalAidKit",
    // Helmets Medic + Crew----------------------------
    "cgqc_helmet_mk1_tank", 
    "cgqc_helmet_mk1_turcotte",
    "cgqc_helmet_crew_black",
    "cgqc_helmet_crew_green", 
    "cgqc_helmet_mk1_medic",
    "cgqc_helmet_mk1_white_medic",
    "cgqc_helmet_mk1_black_medic",
    "cgqc_helmet_mk1_desert_medic", 
    "cgqc_helmet_mk1_mcam_medic",
    "cgqc_helmet_mk1_cadpat_medic",
    "cgqc_helmet_mk1_f_gray_medic", 
    "cgqc_helmet_mk1_f_coyote_medic",
    "cgqc_helmet_mk1_f_black_medic", 
    "cgqc_helmet_mk1_f_green_medic",
    // Vests -----------------------------------
    "cgqc_vest_mk1_driver",
    // Marksman Items ------------------------------
    "ACE_ATragMX", 
    "ACE_Kestrel4500",
    // Binoculars ------------------------------
    "ACE_Vector",
    "ACE_VectorDay",
    // 7.62 -----------------------------------
    "cgqc_gun_mk1_hk417",
    "cgqc_gun_spar17_canpat", 
    "cgqc_gun_spar17_tremblay", 
    "cgqc_gun_spar17_wood", 
    "srifle_EBR_F",
    "srifle_DMR_03_F",
    "srifle_DMR_03_multicam_F", 
    "srifle_DMR_03_khaki_F", 
    "srifle_DMR_03_tan_F", 
    "srifle_DMR_03_woodland_F",
    "rhs_weap_m14ebrri", 
    "Tier1_M110k5",
    // --- Ammo 
    "ACE_20Rnd_762x51_M118LR_Mag", 
    "ACE_20Rnd_762x51_Mk319_Mod_0_Mag", 
    "ACE_20Rnd_762x51_M993_AP_Mag",
    "ACE_20Rnd_762x51_Mag_Tracer",  
    "ACE_20Rnd_762x51_Mag_SD",
    // Explosives -----------------------------------
    "rhsusf_m112_mag",
    "rhsusf_m112x4_mag", 
    "rhsusf_mine_m14_mag",
    "ATMine_Range_Mag",
    "ClaymoreDirectionalMine_Remote_Mag",
    "rhs_mine_M19_mag", 
    "APERSBoundingMine_Range_Mag", 
    "rhs_mine_m2a3b_trip_mag", 
    "rhs_mine_M3_tripwire_mag", 
    "rhs_mine_m3_pressure_mag", 
    "SLAMDirectionalMine_Wire_Mag", 
    "rhs_mine_Mk2_tripwire_mag", 
    "rhs_ec75_mag", 
    "rhs_ec200_mag", 
    "rhs_ec400_mag", 
    "ACE_FlareTripMine_Mag"
]; 