// Sniper backpack 
player addItemToBackpack "ACE_Tripod";
player addItemToBackpack "ACE_ATragMX";
player addItemToBackpack "ACE_Kestrel4500";
player addItemToBackpack "sps_black_hornet_01_Static_F";
player addItemToBackpack "ACE_DefusalKit";
player addItemToBackpack "ACE_M26_Clacker";
player addItemToBackpack "rhsusf_m112_mag";
player addItemToBackpack "rhsusf_m112_mag";
player addItemToBackpack "SLAMDirectionalMine_Wire_Mag";
player addItemToBackpack "SLAMDirectionalMine_Wire_Mag";
player addItemToBackpack "rhsusf_mine_m14_mag";
player addItemToBackpack "rhsusf_mine_m14_mag";
player addItemToBackpack "rhsusf_mine_m14_mag";
player addItemToBackpack "rhsusf_mine_m14_mag";
player addItemToBackpack "rhsusf_mine_m14_mag";
