player addWeapon "rhs_weap_m16a4_imod_grip2";
player addPrimaryWeaponItem "Tier1_KAC_556_QDC_CQB_Black";
player addPrimaryWeaponItem "Tier1_Mk18_NGAL_M300C_Black";
player addPrimaryWeaponItem "Tier1_Shortdot_Geissele_Docter_Black_PIP";
player addPrimaryWeaponItem "Tier1_Harris_Bipod_Black";
player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull";