player addWeapon "cgqc_gun_mk1_m4a1blkII_gl";
player addPrimaryWeaponItem "Tier1_KAC_556_QDC_CQB_Black";
player addPrimaryWeaponItem "Tier1_M4BII_NGAL_M600V_Black";
player addPrimaryWeaponItem "Tier1_Razor_Gen2_16_Geissele_Docter";
player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_Mk262_Stanag_Pull";
player addPrimaryWeaponItem "1Rnd_HE_Grenade_shell";